version: '3'
services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: job_container
      MYSQL_ROOT_PASSWORD: password
  # job:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.php
  #   environment:
  #     - COMPANY_ID=420
